### ISSUE TITLE
Issue running on MacOS

### ISSUE THREAD

**Issue by rbw** [rbw/nawano#3]
Traceback (most recent call last):
  File "/usr/local/bin/nawano", line 7, in <module>
    from nawano.cli import run
  File "/usr/local/lib/python3.7/site-packages/nawano/cli.py", line 5, in <module>
    from nawano.utils import stylize
  File "/usr/local/lib/python3.7/site-packages/nawano/utils.py", line 10, in <module>
    from libn import mrai_from_raw, mrai_to_raw
  File "/usr/local/lib/python3.7/site-packages/libn/__init__.py", line 112, in <module>
    import libn.work
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/libn/work.cpython-37m-darwin.so, 2): Symbol not found: _GOMP_barrier
  Referenced from: /usr/local/lib/python3.7/site-packages/libn/work.cpython-37m-darwin.so
  Expected in: flat namespace
 in /usr/local/lib/python3.7/site-packages/libn/work.cpython-37m-darwin.so

**Comment by rbw** [comment]
I'm not familiar with MacOS (using a friend's Macbook for testing) and might be doing something wrong.

Dependencies are installed using `brew`:
https://github.com/rbw/nawano/blob/branch-0.1.4/README.md#macos

**Comment by nano128** [comment]
Looks like a GCC version issue. I'm not familiar with the way you specified the compiler in readme.

Can you remove libb2-dev and run pip. Pip will fail, but it'll output the compilation command it tried to run. Then we'll know which compiler pip used.

**Comment by nano128** [comment]
pip install nawano --user --verbose --verbose --verbose

this will give all the details with the compilation. no need to uninstall libb2-dev.

**Comment by nano128** [comment]
Actually, can you take a look at the latest commit in nanopy and let me know whether that fixes this issue or not? It should select the compiler from inside the setuptools rather than changing the env variable outside the setup.

**Comment by rbw** [comment]
It might be a bad idea to force `gcc-8`. I'd just go with `gcc` and leave it up to the user to link to a newer version of the compiler.

Errors using `clang` (Linux and MacOS) and OS-default `gcc` on MacOS with OpenCL (--enable-gpu):
https://gist.github.com/rbw/6d6e6a718f592afdc3ac4a6e7469be59

**Comment by nano128** [comment]
not really. I never tried clang. But I know that the OS default gcc will not work. OSX gcc is really old. It was never updated to include omp. So, I don't think the extension will compile with the OS-default gcc.

**Comment by rbw** [comment]
OK. Let's not bother with those old versions then.

What do you think of doing something like this in setup.py to find the latest version of gcc instead of explicitly specifying gcc-8?

```python
import os
import re

GCC_SEARCH_PATH = '/usr/local/bin'

gcc = sorted([f for f in os.listdir(GCC_SEARCH_PATH) if re.match('gcc-[0-9]{1,2}$', f)])

if not gcc:
   raise FileNotFoundError('gcc not found in {0}'.format(GCC_SEARCH_PATH))

os.environ['CC'] = gcc[-1]  # use the most recent gcc found in GCC_SEARCH_PATH
```

**Comment by nano128** [comment]
Yeah that is definitely a better solution. One small issue that has to be fixed is that 'GCC_SEARCH_PATH' could vary among operating systems. For me it is /usr/bin. But thinking along this line, the code below could be a solution.

`def which(pgm):
    path=os.getenv('PATH')
    for p in path.split(os.path.pathsep):
        p=os.path.join(p,pgm)
        if os.path.exists(p) and os.access(p,os.X_OK):
            return p

os.environ["CC"] = "gcc"
if sys.platform == 'darwin':
    gcc=None
    for i in range(9, 5, -1):
        gcc = 'gcc-'+str(i)
        if which(gcc):
            os.environ["CC"] = gcc
            break
`

We are also indirectly specifying that the minimum gcc version we need is gcc-5.

**Comment by rbw** [comment]
solved. thanks for helping out @nano128
